import type { Metadata } from "next";

import { LegalShell } from "@/components/LegalShell";
import { CONTACT_EMAIL } from "@/lib/links";

export const metadata: Metadata = {
  title: "Terms of service",
  description:
    "The terms that apply to using first-ocean.com, including the limits of the valuation estimate.",
  alternates: { canonical: "/terms" },
};

// TODO: legal review before launch. This is an ASSUMPTION, not a known fact:
// firstocean's registered jurisdiction was never confirmed. Change it here if
// it is wrong, and the governing-law clause below follows.
const GOVERNING_LAW = "England and Wales";

export default function TermsPage() {
  return (
    <LegalShell title="Terms of service" updated="9 August 2026">
      <p>
        These terms apply to first-ocean.com. Using the site means you accept
        them. If you are agreeing on behalf of a company, you are confirming
        that you can bind it.
      </p>

      <section>
        <h2>What the site is</h2>
        <p>
          This site describes what firstocean does and lets you book a call. It
          also offers a tool that estimates what an asset&rsquo;s unused
          emerging-market rights might be worth. Nothing here is an offer, and
          nothing here creates a commercial relationship on its own.
        </p>
      </section>

      <section>
        <h2>The estimate is not advice</h2>
        <p>
          The valuation tool produces a directional model from the handful of
          answers you give it. It is generated by a language model, it is not a
          formal valuation, and it is not financial, investment, legal, tax or
          regulatory advice. It has not been prepared by a qualified valuer and
          it does not account for your specific circumstances. Do not rely on it
          for a transaction, a filing, or a board decision. Take professional
          advice instead.
        </p>
      </section>

      <section>
        <h2>How you may use the site</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            scrape, crawl or bulk-extract the site beyond ordinary browsing
          </li>
          <li>
            attempt to interfere with the site or gain access you were not
            granted
          </li>
          <li>
            use the site to break the law, or to infringe anyone&rsquo;s rights
          </li>
          <li>
            present output from the estimate tool as an independent valuation
          </li>
        </ul>
      </section>

      <section>
        <h2>Our content</h2>
        <p>
          The site, its copy, and its design belong to firstocean. You may read
          it, link to it, and quote reasonable extracts with attribution. You
          may not copy it wholesale or reuse it as your own marketing material.
        </p>
      </section>

      <section>
        <h2>Availability</h2>
        <p>
          The site is provided as it is. We do not promise it will be
          uninterrupted or error-free, and we may change or withdraw any part of
          it, including the estimate tool, without notice.
        </p>
      </section>

      <section>
        <h2>Liability</h2>
        <p>
          To the extent the law allows, we are not liable for any loss of
          profit, revenue, business, or data, or for any indirect or
          consequential loss, arising from your use of the site or your reliance
          on anything it produces. Nothing here limits liability for death or
          personal injury caused by negligence, for fraud, or for anything else
          that cannot lawfully be limited.
        </p>
      </section>

      <section>
        <h2>Changes and governing law</h2>
        <p>
          We may update these terms. The version on this page is the one that
          applies. These terms are governed by the laws of {GOVERNING_LAW}, and
          its courts have exclusive jurisdiction, unless mandatory law where you
          live says otherwise.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          Questions go to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </p>
      </section>
    </LegalShell>
  );
}
